# Generated by Django 3.2.2 on 2021-05-08 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('surname', models.CharField(max_length=30)),
                ('status', models.CharField(choices=[('STUD', 'Student'), ('TEAC', 'Teacher'), ('MENT', 'Mentor'), ('ADMN', 'Administration'), ('CUST', 'Customer')], max_length=4)),
                ('telegram', models.CharField(max_length=60)),
                ('mail', models.EmailField(max_length=254)),
                ('curr_task', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=60)),
                ('status', models.CharField(choices=[('OK', 'Completed'), ('PR', 'In progress'), ('NS', 'Not started yet')], max_length=2)),
                ('progress', models.CharField(max_length=3)),
                ('startdate', models.DateTimeField(auto_now=True)),
                ('completedate', models.DateTimeField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.IntegerField()),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=100)),
                ('deadline', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prodtoring.project')),
                ('responsible', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='prodtoring.person')),
            ],
        ),
    ]
