# Generated by Django 3.2.2 on 2021-05-08 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prodtoring', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='project',
            field=models.ManyToManyField(to='prodtoring.Project'),
        ),
    ]
